// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4s9vpPVksaVvFY70Zi4yAlskLF9UlRsY',
    appId: '1:936351806230:web:6094d69ae84675a99f9637',
    messagingSenderId: '936351806230',
    projectId: 'first-steps-6fd6df',
    authDomain: 'first-steps-6fd6df.firebaseapp.com',
    storageBucket: 'first-steps-6fd6df.firebasestorage.app',
    measurementId: 'G-PRB2P81RKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zgsgpFEjWK4OgqUNfgQJBenhnbZ-Xkc',
    appId: '1:936351806230:android:60336d0dd06e4fc09f9637',
    messagingSenderId: '936351806230',
    projectId: 'first-steps-6fd6df',
    storageBucket: 'first-steps-6fd6df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_YdshgcgYJHZjhuu6yWR7ZKO-gWMuqw',
    appId: '1:936351806230:ios:3e85d95e50eeee6b9f9637',
    messagingSenderId: '936351806230',
    projectId: 'first-steps-6fd6df',
    storageBucket: 'first-steps-6fd6df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirstSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_YdshgcgYJHZjhuu6yWR7ZKO-gWMuqw',
    appId: '1:936351806230:ios:3e85d95e50eeee6b9f9637',
    messagingSenderId: '936351806230',
    projectId: 'first-steps-6fd6df',
    storageBucket: 'first-steps-6fd6df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirstSteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4s9vpPVksaVvFY70Zi4yAlskLF9UlRsY',
    appId: '1:936351806230:web:adf87b196481441f9f9637',
    messagingSenderId: '936351806230',
    projectId: 'first-steps-6fd6df',
    authDomain: 'first-steps-6fd6df.firebaseapp.com',
    storageBucket: 'first-steps-6fd6df.firebasestorage.app',
    measurementId: 'G-SBKTGGW1LH',
  );
}
